<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OnMuhasebe.DataAccess\OnMuhasebe.DataAccess.csproj" />
    <ProjectReference Include="..\OnMuhasebe.Models\OnMuhasebe.Models.csproj" />
    <ProjectReference Include="..\OnMuhasebe.Utility\OnMuhasebe.Utility.csproj" />
  </ItemGroup>

</Project>
