<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OnMuhasebe.Infrastructure\OnMuhasebe.Infrastructure.csproj" />
    <ProjectReference Include="..\OnMuhasebe.Domain\OnMuhasebe.Domain.csproj" />
    <ProjectReference Include="..\OnMuhasebe.Utility\OnMuhasebe.Utility.csproj" />
  </ItemGroup>

</Project>
