// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnMuhasebe.DataAccess;

#nullable disable

namespace OnMuhasebe.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909132858_AddModelsToDb")]
    partial class AddModelsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnMuhasebe.Models.AlisFaturaSatiri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlisFaturaId")
                        .HasColumnType("int");

                    b.Property<int>("AlisFaturasiId")
                        .HasColumnType("int");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SatirTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StokId")
                        .HasColumnType("int");

                    b.Property<int>("StokKartiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlisFaturasiId");

                    b.HasIndex("StokKartiId");

                    b.ToTable("AlisFaturaSatirlari");
                });

            modelBuilder.Entity("OnMuhasebe.Models.AlisFaturasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AraToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CariId")
                        .HasColumnType("int");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GenelToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KdvToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("AlisFaturalari");
                });

            modelBuilder.Entity("OnMuhasebe.Models.Cari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("CariKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("CariTipi")
                        .HasColumnType("tinyint");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiDairesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cariler");
                });

            modelBuilder.Entity("OnMuhasebe.Models.CariHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Alacak")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BelgeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Borc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CariId")
                        .HasColumnType("int");

                    b.Property<string>("IslemTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OdemeTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("CariHareketler");
                });

            modelBuilder.Entity("OnMuhasebe.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("OnMuhasebe.Models.Parametre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParametreDegeri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParametreKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parametreler");
                });

            modelBuilder.Entity("OnMuhasebe.Models.SatisElemani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SatisElemanlari");
                });

            modelBuilder.Entity("OnMuhasebe.Models.SatisFaturaSatiri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SatirTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SatisFaturaId")
                        .HasColumnType("int");

                    b.Property<int>("SatisFaturasiId")
                        .HasColumnType("int");

                    b.Property<int>("StokId")
                        .HasColumnType("int");

                    b.Property<int>("StokKartiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SatisFaturasiId");

                    b.HasIndex("StokKartiId");

                    b.ToTable("SatisFaturaSatirlari");
                });

            modelBuilder.Entity("OnMuhasebe.Models.SatisFaturasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AraToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CariId")
                        .HasColumnType("int");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GenelToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KdvToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SatisElemaniId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("SatisElemaniId");

                    b.ToTable("SatisFaturalari");
                });

            modelBuilder.Entity("OnMuhasebe.Models.StokHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelgeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HareketTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StokId")
                        .HasColumnType("int");

                    b.Property<int>("StokKartiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("StokKartiId");

                    b.ToTable("StokHareketler");
                });

            modelBuilder.Entity("OnMuhasebe.Models.StokKarti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<decimal>("AlisFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KritikStok")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SatisFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StokAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StokKartlari");
                });

            modelBuilder.Entity("OnMuhasebe.Models.AlisFaturaSatiri", b =>
                {
                    b.HasOne("OnMuhasebe.Models.AlisFaturasi", "AlisFaturasi")
                        .WithMany("AlisFaturaSatirlari")
                        .HasForeignKey("AlisFaturasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnMuhasebe.Models.StokKarti", "StokKarti")
                        .WithMany("AlisFaturaSatirlari")
                        .HasForeignKey("StokKartiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlisFaturasi");

                    b.Navigation("StokKarti");
                });

            modelBuilder.Entity("OnMuhasebe.Models.AlisFaturasi", b =>
                {
                    b.HasOne("OnMuhasebe.Models.Cari", "Cari")
                        .WithMany("AlisFaturalari")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnMuhasebe.Models.Kullanici", "Kullanici")
                        .WithMany("AlisFaturalari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cari");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("OnMuhasebe.Models.CariHareket", b =>
                {
                    b.HasOne("OnMuhasebe.Models.Cari", "Cari")
                        .WithMany("CariHareketleri")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnMuhasebe.Models.Kullanici", "Kullanici")
                        .WithMany("CariHareketleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cari");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("OnMuhasebe.Models.SatisFaturaSatiri", b =>
                {
                    b.HasOne("OnMuhasebe.Models.SatisFaturasi", "SatisFaturasi")
                        .WithMany("SatisFaturaSatirlari")
                        .HasForeignKey("SatisFaturasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnMuhasebe.Models.StokKarti", "StokKarti")
                        .WithMany("SatisFaturaSatirlari")
                        .HasForeignKey("StokKartiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SatisFaturasi");

                    b.Navigation("StokKarti");
                });

            modelBuilder.Entity("OnMuhasebe.Models.SatisFaturasi", b =>
                {
                    b.HasOne("OnMuhasebe.Models.Cari", "Cari")
                        .WithMany("SatisFaturalari")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnMuhasebe.Models.Kullanici", "Kullanici")
                        .WithMany("SatisFaturalari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnMuhasebe.Models.SatisElemani", "SatisElemani")
                        .WithMany("SatisFaturalari")
                        .HasForeignKey("SatisElemaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cari");

                    b.Navigation("Kullanici");

                    b.Navigation("SatisElemani");
                });

            modelBuilder.Entity("OnMuhasebe.Models.StokHareket", b =>
                {
                    b.HasOne("OnMuhasebe.Models.Kullanici", "Kullanici")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnMuhasebe.Models.StokKarti", "StokKarti")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("StokKartiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("StokKarti");
                });

            modelBuilder.Entity("OnMuhasebe.Models.AlisFaturasi", b =>
                {
                    b.Navigation("AlisFaturaSatirlari");
                });

            modelBuilder.Entity("OnMuhasebe.Models.Cari", b =>
                {
                    b.Navigation("AlisFaturalari");

                    b.Navigation("CariHareketleri");

                    b.Navigation("SatisFaturalari");
                });

            modelBuilder.Entity("OnMuhasebe.Models.Kullanici", b =>
                {
                    b.Navigation("AlisFaturalari");

                    b.Navigation("CariHareketleri");

                    b.Navigation("SatisFaturalari");

                    b.Navigation("StokHareketleri");
                });

            modelBuilder.Entity("OnMuhasebe.Models.SatisElemani", b =>
                {
                    b.Navigation("SatisFaturalari");
                });

            modelBuilder.Entity("OnMuhasebe.Models.SatisFaturasi", b =>
                {
                    b.Navigation("SatisFaturaSatirlari");
                });

            modelBuilder.Entity("OnMuhasebe.Models.StokKarti", b =>
                {
                    b.Navigation("AlisFaturaSatirlari");

                    b.Navigation("SatisFaturaSatirlari");

                    b.Navigation("StokHareketleri");
                });
#pragma warning restore 612, 618
        }
    }
}
